### ISSUE TITLE
posXY unit is 'tiles' even if room is in meters (#216 OGrEE-3D)

### ISSUE THREAD

**Issue by helderbetiol** [ditrit/OGrEE-CLI#100]
[Cedrok](https://github.com/Cedrok) commented [on Jun 7](https://github.com/ditrit/OGrEE-CLI/issues/new#issuecomment-1148482128)
It's a CLI issue: by the posXYUnit is "tile" by default.
We need to retrieve the floorUnit attribute from parent room and map it to posXYUnit.

room.attributes[floorUnit] = "t" => rack.attributes[posXYUnit] = "tile"
room.attributes[floorUnit] = "m" => rack.attributes[posXYUnit] = "meter"
room.attributes[floorUnit] = "f" => rack.attributes[posXYUnit] = "foot"

**Comment by helderbetiol** [comment]
Selon Cédric, pour le cas d'un rack:
- posXYUnit sera toujours le floorUnit de la parent room
- sizeUnit & heightUnit sont OK avec les valeurs par défaut
- height et orientation sont obligatoirement donnés en param

**Comment by denizul** [comment]
We have 2 fixes, one on the API (issue216AlwaysTiles 613d9751ccc) and one on the CLI (issue100_posXY 6aca2f9fc). We believe the fix on the CLI to be the better one to use
