### ISSUE TITLE
Non Square buildings

### ISSUE THREAD

**Issue by Novanef** [ditrit/OGrEE-CLI#115]
- [x] add building templates
```json
{
  "slug"          : "",
  "orientation"   : "",
  "sizeWDHm"      : [ 0, 0, 0 ],
  "vertices" : [
    [ 0, 0 ],
    [ 0, 30],
    ...
  ]
}
```

Type     | Attribute     | Comment
---------|---------------|---------- 
string   | slug          | Name used for using the template, without spaces or points.
string   | orientation   | List of possible orientations [here](https://github.com/ditrit/OGREE-3D/wiki/How-it-works#Orientations).
float[]  | sizeWDHm      | Size of the building in meter.
int[2][]| vertices | Coordinates of the corners of the building

- [x] add a +building syntax with templates : `+building:[name]@[pos]@[template]`

**Comment by denizul** [comment]
Creating and using building templates is now functional on issue116Orientation branch as of c8621267
This must also be used respectively with the issue116Orientation branch of the API

**Comment by Cedrok** [comment]
Unable to load a building template. The CLI asks all the field of a room template.
For reminder, what we want for a building template is described [here ](https://github.com/ditrit/OGrEE-3D/wiki/Rework-orientations#building-templates).
