### ISSUE TITLE
Non standard orientation for rooms and buildings

### ISSUE THREAD

**Issue by Novanef** [ditrit/OGrEE-CLI#116]
- [x] add float orientation in degrees and -|+ **W|E** -|+ **N|S** for `+building` 
    +building:[name]@[pos]@[size]**@[orientation]**
    `+building:CED.ST.BD@[0,0]@[50,50,]@45`
    `+building:CED.ST.BD@[0,0]@[50,50,]@+N+W`

- [x] add float orientation in degress for building templates #115 

- [x] add float orientation in degrees for `+room`
    `+room:CED.ST.BD.RO@[0,0]@[20,20]@60@t`
 
- [x] add float orientation in degress for room templates

**Comment by denizul** [comment]
Added as of c8621267 on issue116Orientation branch 
This works only if paired with the respective issue116Orientation branch of the API

**Comment by Cedrok** [comment]
New specifications: https://github.com/ditrit/OGrEE-3D/wiki/Rework-orientations
- [ ] site cmd
- [ ] building cmd
- [ ] room cmd
- [ ] room template (if check is done here)

**Comment by denizul** [comment]
The new specifications have been added as of 44606382b on 'reworkOrientations'
