### ISSUE TITLE
 rack : posZ <> 0

### ISSUE THREAD

**Issue by Novanef** [ditrit/OGrEE-CLI#122]
for cable tree
for wall racks

posZ should be set to something <> 0

**Comment by helderbetiol** [comment]
The idea is to implement a new mandatory attribute to create a rack that replaces the current posXY: poXYZ. Its value will always be a Vector3, for example: {"x":25.0,"y":29.4,"z":5.0}". In the cases where a Vector2 would have been enough, a Vector3 will be sent with the z coordinate set to 0.

To implement it on the API side, we should verify that posXYZ is in the attributes list and in a valid Vector3 format.

**Comment by denizul** [comment]
Added posXYZ as a rack attribute on branch 'issue122posZ' this must be paired with the respective branch of the API

**Comment by denizul** [comment]
Merged into master as of 348fdd7ec
