### ISSUE TITLE
dbForTenants : +domain:NAME@color

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGrEE-CLI#152]
add +domain command in /Ogranization namespace

exactly like +tenant in /Physical

cf API#50 for the backend https://github.com/ditrit/OGrEE-API/issues/50

**Comment by denizul** [comment]
Fixed. The changes now are that we have a new command that allows us to create domains:
```
+domain:PATH/DOMAIN_NAME@COLOR      
User must specify the path, DOMAIN_NAME and COLOR   

Where COLOR should be a 6 digit HEX Value (ie 00000A)
```
