### ISSUE TITLE
object  / attribute seprator : change "." to ":"

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGrEE-CLI#18]
replace ".attr"

+group:EDF.NOE.BI2.C8.LANcore@{B03b,C03b}
       EDF.NOE.BI2.C8.LANcore.description1=LAN Core
       EDF.NOE.BI2.C8.LANcore.description2=2 x N7K 10 slots
       EDF.NOE.BI2.C8.LANcore.label=#description
       EDF.NOE.BI2.C8.LANcore.domain=exaion_lan

by ":attr"

+group:EDF.NOE.BI2.C8.LANcore@{B03b,C03b}
       EDF.NOE.BI2.C8.LANcore:description1=LAN Core
       EDF.NOE.BI2.C8.LANcore:description2=2 x N7K 10 slots
       EDF.NOE.BI2.C8.LANcore:label=#description
       EDF.NOE.BI2.C8.LANcore:domain=exaion_lanv

**Comment by denizul** [comment]
This is done already but please note due to recent changes you cannot assign directly to words, it must be in a string format. Example
`
EDF.NOE.BI2.C8.LANcore:description1="LAN Core"
`
