### ISSUE TITLE
camera.wait error 

### ISSUE THREAD

**Issue by Cedrok** [ditrit/OGrEE-CLI#30]
Change content of camera.wait command : put a *serialized Vector3* instead of *null* for "position"
```
{
  "command"  : "wait",
  "position" : "{"x":0, "y":0, "z":0}",
  "rotation" : "{"x":999, "y":time}"
}
```
From Unity side, a Vector3 can't be null in a serialized structure

**Comment by denizul** [comment]
Issue fixed in latest commit on dev branch
