### ISSUE TITLE
Use room template on room creation

### ISSUE THREAD

**Issue by Cedrok** [ditrit/OGrEE-CLI#33]
To simplify room creation, we can use a template which describe all its attributes at once
```
+room:[name]@[pos]@[template]

+ro:[name]@[pos]@[template]
```

More details in Nextcloud/Ogree/5_Misc/CliTemplateUsage.md

**Comment by Cedrok** [comment]
2 issues with current implementations:

- Unrecognised command with a room slug with a "."
```
asher@OGrEE3D:/Physical$> +ro:DEMO/ALPHA/B/R1@[0,0]@demo.R1
OGREE: Unrecognised command!
```

- **reserved** and **technical** attributes need to be refined like you did with the *room:areas* command

**Comment by denizul** [comment]
The reserved and technical attributes are working, this was fixed on Friday. For the names I suggest to not use '.' because it confuses the parser
