### ISSUE TITLE
add LSU and GETU commands when in a rack / lsslot / getslots for any object

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGrEE-CLI#35]
lsu : list all children in a rack , sorted by U
lsslot : list all children in a rack , sorted by slot name

getu : 35 : return object inserted into U 35 or current rack, if exits
getslot <name> : return object inserted into <slot> if  exists

**Comment by denizul** [comment]
All of these commands are now added as of the latest commit today on the 'dev' branch
