### ISSUE TITLE
Error in path on Windows build

### ISSUE THREAD

**Issue by Cedrok** [ditrit/OGrEE-CLI#37]
There is an issue with all paths in the Windows CLI:
- `ls` and `cd` commands:
![image](https://user-images.githubusercontent.com/35805113/173069642-d01fb222-3940-4a32-bce2-3d83d594dfbf.png)

- `cd ../Logical/` crashes the CLI

The CLI is currently disable to see objects in DB, to move through objects....

**Comment by denizul** [comment]
Confirmed that it is fixed with Cedric
