### ISSUE TITLE
verbosity level not correct

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGrEE-CLI#41]
./main -v [0..4]

please update your code to match those points

ARGS with "-" are only one char
ARGS with "--" are full name

I would prefer instead of 0..4

0 => NONE
1 => ERRORS
2 => WARNING (includes ERRORS)
3 => INFO (includes W + E)
4 => DEBUG (all messages) 

each message has to have a verbosity level.

NONE mean, no output
INFO : 
```
./main --verbose INFO ...
Connected to UNITY through <url>
Connected to API through <url>
```

DEBUG
```
./main --verbose DEBUG ...
Connected to UNITY through <url>
Connected to API through <url> with <apikey>
API is connected to DB <instance/tenant>  through <url>
```

**Comment by denizul** [comment]
Fixed on latest commit
