### ISSUE TITLE
ls<object> in <object>'s parent directroy / No recursive

### ISSUE THREAD

**Issue by hchybz** [ditrit/OGrEE-CLI#47]
please modify ls<object> bhaviour so that 👍 

- [ ] ls<object> (no arg)  = ls<object> .
- [ ] ls<object> should NOT be recursive
- [ ] ls<object> should only display results when we are in <parent> directory

`TEN.SITE.BD.ROOM > lsrack ` => should display results
`TEN.SITE.BD` > lsrack  => should NOT display anything because racks must children of room

**Comment by GeremWD** [comment]
A bit more complicated than planned, maybe the LSOBJECT function should be simplified.

**Comment by denizul** [comment]
Resolved and and merged into master as of 129401af
