### ISSUE TITLE
Errors with paths on .template commands

### ISSUE THREAD

**Issue by Cedrok** [ditrit/OGrEE-CLI#57]
Only works when the path is stored in variables at least partially.

**Comment by hchybz** [comment]
when path/name contains special char.. does not work

OK : `.template:${3DMODELS}Schroff/Schroff_10130-286_800_1200_2000_42u_Side-by-side_cabinet.json`

KO : `.template:${3DMODELS}Schroff/Schroff_(10130-276)_800_1000_2000_42u_Side-by-side_cabinet.json`

**Comment by denizul** [comment]
Error no longer persists
