### ISSUE TITLE
Corridor creation

### ISSUE THREAD

**Issue by Cedrok** [ditrit/OGrEE-CLI#59]
- [x] Error on syntax
The "temperature" attribute for a corridor is ONLY "cold" or "warm". 

- [x] Incorrect structure
A corridor should respect the [standard structure for an OgreeObject](https://github.com/ditrit/OGrEE-3D/wiki/How-it-works)
As specified by the doc, the limits of a corridor are stored in a "content" attribute with "short" names (without its parents)
The color attributes is automaticaly generated by the 3D client 

Example of a corridor:
```json
{
    "attributes": {
        "color": "000099",
        "content": "A01,B05",
        "temperature": "cold"
    },
    "category": "corridor",
    "children": null,
    "createdDate": "2022-09-23T12:54:18.703Z",
    "description": [],
    "domain": "CED",
    "id": "632dac7a65454669d5b74009",
    "lastUpdated": "2022-09-23T12:54:20.71Z",
    "name": "COR",
    "parentId": "632c7c41a5b1dc6a2b0aa709"
}
```

**Comment by Cedrok** [comment]
```
+co:CED.BETA.A.R1.C_AB@{A01,B09}@cold

{
    "attributes": {
        "color": "ced666",
        "content": "A01,A01",
        "temperature": "cold"
    },
    "category": "corridor",
    "createdDate": "2022-10-10T07:28:42.663Z",
    "description": [],
    "domain": "CED",
    "id": "6343c9aaee31e049f2683c90",
    "lastUpdated": "2022-10-10T07:28:42.663Z",
    "name": "C_AB",
    "parentId": "632b395cbebec2b71c7a714d"
}
```
- Wrong "content" for a newly created corridor: should be **A01,B09**
- If temperature is "cold", then the color is "000099" / If temperature is "warn", then color is "990000"

**Comment by Cedrok** [comment]
```
+co:CED.BETA.A.R1.C_ERR1@{A01,C42}@cold
```
The rack *CED.BETA.A.R1.C42* doesn't exist. An error should be raised to prevent creating a corridor with an unknown corner

**Comment by denizul** [comment]
I pushed updates to API and CLI

**Comment by Cedrok** [comment]
Ok for the content. 
There are still errors with color depending on temperature & creation with non-existing rack.

**Comment by denizul** [comment]
I tested this and I am not able to reproduce the errors that you mentioned. Did you make sure to update the API and switch to the branch 'groupSpecUpdate'?

**Comment by Cedrok** [comment]
Works fine with lastest commits from OGrEE-CLI/createCorridor & OGrEE-API/corridorSpecUpdate
