### ISSUE TITLE
Some commands are broken on master branch

### ISSUE THREAD

**Issue by denizul** [ditrit/OGrEE-CLI#61]
Commands such as gt, update are broken on master branch

**Comment by hchybz** [comment]
any detail about this issue ?

**Comment by hchybz** [comment]
- lsten
..

**Comment by GeremWD** [comment]
I believe this should be splitted into different issues.

**Comment by denizul** [comment]
I agree, I will create respective issues when I am certain of all the features that are broken

**Comment by GeremWD** [comment]
Can I close this ?
