### ISSUE TITLE
Error handling for some interact commands

### ISSUE THREAD

**Issue by Cedrok** [ditrit/OGrEE-CLI#76]
There is no error handling for some commands. Their values should be only `true` or `false`.
- [x] [roomName]:tilesName
- [x] [roomName]:tilesColor
- [x] [rackName]:U
- [x] [rackName]:slots
- [x] [rackName]:localCS
- [x] [deviceName]:slots
- [x] [deviceName]:localCS

For example, this should not be send :
```
cedrok@OGrEE3D:/Physical$> CED.FBX.A.R1:tilesName=patate
OK. Attempting to update...
Success
Room modifier detected
JSON:  {"tilesName":"patate"}
DEBUG VIEW THE JSON
JSON:  {"data":{"id":"635a8e221f69cc9342a3d73c","param":"tilesName","value":"patate"},"type":"interact"}
```

**Comment by denizul** [comment]
Resolved as of 3a9819c4 on 'dev' branch
