### ISSUE TITLE
Wrong behavior of group:content command 

### ISSUE THREAD

**Issue by Cedrok** [ditrit/OGrEE-CLI#79]
The command: `[groupName]:content=[true|false]`
It should be an interact command for the 3D client.
```json
{
  "data":
  {
    "id":"",
    "param":"content",
    "value":""
  },
  "type":"interact"
}
```

**Comment by denizul** [comment]
The issue was that certain update commands would only work on objects on the physical domain. This was resolved on the dev branch as of d6b77c11
