### ISSUE TITLE
Label command no longer works

### ISSUE THREAD

**Issue by Cedrok** [ditrit/OGrEE-CLI#80]
`<name>:label=<value>` with <value> is a string or an attribute given with `#attribute`
More details [here](https://github.com/ditrit/OGrEE-3D/wiki/CLI-langage#labels)
```
cedrok@OGrEE3D:/Physical/CED/BETA/A/R1$> B09:label=potato
Error : Only boolean values can be used for interact commands
```

**Comment by denizul** [comment]
Restored as of 2cbb784f on 'dev' branch
