### ISSUE TITLE
Object's attributes collection should be only strings

### ISSUE THREAD

**Issue by Cedrok** [ditrit/OGrEE-CLI#81]
All attributes stored in `object.attributes` should be strings as object.attributes is a Dictionary<string,string>.
If we write:
```
DEMO.ALPHA:gps=[1,2,0]
```
The *gps* attribute should be a string, not a int[].

A workaround is using quotes, but there shouldn't be something else than strings in attributes.

**Comment by denizul** [comment]
Merged into master as of 8d3dff4d0
