### ISSUE TITLE
undraw command to remove object only in 3D client

### ISSUE THREAD

**Issue by Cedrok** [ditrit/OGrEE-CLI#94]
`undraw` -> remove all objects in Unity
Send a "delete" command with an empty id to 3D client
```json
{
  "type" : "delete",
  "data" : ""
}
```
`undraw [name]` -> remove given objct in Unity
Send a "delete" command with the id of the object to delete to 3D client
```json
{
  "type" : "delete",
  "data" : "id"
}
```

**Comment by denizul** [comment]
resolved and merged into master branch as of 6e4ba6a1
